### ISSUE TITLE
ac运行的时候无法安装依赖

### ISSUE THREAD

**Issue by fhqswcan** [lunnlew/AutoSignMachine#16]
ac运行的时候无法安装依赖

**Comment by fhqswcan** [comment]
![1](https://user-images.githubusercontent.com/12725476/105829203-04fe3580-5fff-11eb-8eef-e0eacf59c8b5.png)

**Comment by fhqswcan** [comment]
已经发现问题 并解决

**Comment by Jenny509135** [comment]
大佬求完整安装教程
