### ISSUE TITLE
My money was stolen！

### ISSUE THREAD

**Issue by babyhub91** [lunnlew/AutoSignMachine#45]
What you share，It has caused me economic losses.I hope you can see what went wrong！
![71f67e6b3520f7ba](https://user-images.githubusercontent.com/78399928/106554829-24ddae00-6557-11eb-9f18-3b8a63ac937e.jpg)

**Comment by lunnlew** [comment]
Please confirm your consumption details, whether you have already owed fees, there is no consumption logic in this script

**Comment by mixool** [comment]
联通app 查询 实时话费

**Comment by mmkkdr** [comment]
煞笔吧，代码写得明明白白，你欠尼玛的费，自己怎么欠的心里没数嘛，草泥马的SB

**Comment by jaysherlock** [comment]
![photo_2021-02-02_15-01-48](https://user-images.githubusercontent.com/44055680/106564909-e05b0e00-6568-11eb-9544-3c232be0ce01.jpg)
You’re really bullshit!

**Comment by qilin7** [comment]
兄弟，为啥讲英语

**Comment by YorkPeng** [comment]
Please give more evidence to prove your words. If it is fake, your whole family will be wiped from the earth. you bastard

**Comment by kelo495** [comment]
傻逼吧，能用中国联通和bilibili的人还整英语。人家开源的代码写的明明白白，你不服可以自己审计，别搁着逼逼赖赖。小学生吗？

**Comment by kelo495** [comment]
给大家看看这臭傻逼孤儿的嘴脸
![Uploading IMG_20210202_162136_315.jpg…]()

**Comment by kelo495** [comment]
给大家看看这臭傻逼孤儿的嘴脸
![Uploading IMG_20210202_162136_315.jpg…]()

**Comment by kelo495** [comment]
给大家看看这臭傻逼孤儿的嘴脸
![IMG_20210202_162136_315](https://user-images.githubusercontent.com/76242317/106573027-181b8300-6574-11eb-861d-48b97a0bb749.jpg)

**Comment by dhbowen1** [comment]
欠费你心里没点B数怎么回事

**Comment by kelo495** [comment]
王培玉 山东泰安 15665710010
![1612255981700](https://user-images.githubusercontent.com/76242317/106576064-b6f5ae80-6577-11eb-82e0-e8f48c97967a.jpeg)
![1612256006939](https://user-images.githubusercontent.com/76242317/106576077-b9f09f00-6577-11eb-89f3-a29831dcc48d.jpeg)
![1612256025464](https://user-images.githubusercontent.com/76242317/106576084-bc52f900-6577-11eb-99aa-f509da765cc8.jpeg)

**Comment by gold2wave** [comment]
> ![IMG_20210202_170148](https://user-images.githubusercontent.com/76242317/106576640-5c108700-6578-11eb-894e-4426303bb110.jpg)
> 
> ![IMG_20210202_165932](https://user-images.githubusercontent.com/76242317/106576557-400ce580-6578-11eb-87a0-6c5f98cba678.jpg)
> ![IMG_20210202_165947](https://user-images.githubusercontent.com/76242317/106576563-41d6a900-6578-11eb-9648-d584b5ce6a1d.jpg)
> 
> ![IMG_20210202_170421](https://user-images.githubusercontent.com/76242317/106577092-e953db80-6578-11eb-908d-3592f9656711.jpg)
> 
> 王** 山东泰安 156xxxx3578 131xxxx2669 153xxxx0226
> 96年的小孩子应该懂点事 这次打码是给你留个面子 请删除issues给作者道歉

牛逼啊兄得
