### ISSUE TITLE
流量领取无效

### ISSUE THREAD

**Issue by axh2018** [lunnlew/AutoSignMachine#49]
![Screenshot_20210203_145911_com.termux.jpg](https://user-images.githubusercontent.com/58505743/106710367-cc7adf00-6630-11eb-84fb-d86a26dab617.jpg)
![Screenshot_20210203_150332_com.termux.jpg](https://user-images.githubusercontent.com/58505743/106710507-021fc800-6631-11eb-8673-362d98223034.jpg)
如图，只是签到和一些抽奖任务，并没有去玩游戏，“每天领3g”任务。

**Comment by Silicon-95** [comment]
时间未到

**Comment by axh2018** [comment]
> 
> 
> 时间未到

那就是要一直循环运行这个脚本吗？
