### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module 'yargs/yargs'

### ISSUE THREAD

**Issue by lly8666** [lunnlew/AutoSignMachine#7]
nodejs模式，明明安装了yargs，却一直提示这个错误。
PS：更新前的版本没这个问题，最新版有。不知道是我nodejs配置有问题还是怎么回事。

**Comment by mixool** [comment]
npm install 
然后再把提示的消息再操作一遍，我好像是这么解决的

**Comment by lly8666** [comment]
> npm install
> 然后再把提示的消息再操作一遍，我好像是这么解决的

好像是依赖安装路径问题。实在不会玩nodejs，哈哈哈。
