### ISSUE TITLE
大佬你的docker镜像是不是没了？

### ISSUE THREAD

**Issue by s1sunny** [lunnlew/AutoSignMachine#8]
大佬你的docker镜像是不是没了？
另外求联通多账号签到。

**Comment by s1sunny** [comment]
是我小白自己不懂构建，问题关闭。现在有新问题的
构建过程出现错误。。。
Step 3/9 : RUN apk add --no-cache tzdata nodejs npm
 ---> Running in 86769d86c702
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/aarch64/APKINDEX.tar.gz

**Comment by lunnlew** [comment]
更新了国内源，应该快点
