### ISSUE TITLE
联通签到任务多账号

### ISSUE THREAD

**Issue by bugme2** [lunnlew/AutoSignMachine#9]
弄了多账号配置文件，执行的时候能读取全部账号的积分，但是做签到任务的时候只做了一个账号的，重复执行也是如此。

**Comment by qilin7** [comment]
如果有别的手机，试试不同手机号对应不同的appid，我没别的手机测试。

**Comment by angelfish110** [comment]
> 弄了多账号配置文件，执行的时候能读取全部账号的积分，但是做签到任务的时候只做了一个账号的，重复执行也是如此。

多帐号怎么弄呀，求指点，不太懂，那个命令怎么写
